# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: galio
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with your npm package path
custom: # Replace with a single custom sponsorship URL